# Generated by Django 3.2.25 on 2024-07-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_Import_regiones'),
        ('todoapp', '0002_mascota_usuario'),
    ]

    operations = [
    ]
