# Generated by Django 5.0.7 on 2024-07-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_merge_0002_Import_regiones_0002_mascota_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosmascota',
            name='archivo',
            field=models.ImageField(upload_to='static/todoapp/fotos_mascota/'),
        ),
    ]
