# Generated by Django 5.0.4 on 2024-07-16 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_fotosmascota_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='ubicacion_extravio',
        ),
        migrations.AddField(
            model_name='mascota',
            name='comuna_extravio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.comuna'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='region_extravio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.region'),
        ),
        migrations.AlterField(
            model_name='fotosmascota',
            name='archivo',
            field=models.ImageField(upload_to=''),
        ),
    ]
